config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories do
    resources :posts, only: [:new, :create, :destroy]
  end
  resources :posts, except: [:new, :create, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, format: { with: /\A[A-Z][a-z]+ [a-z]{2,}\.\z/,
                                             message: 'Minimum it should be 2 words with 2 letters each. Should also contain "." and first word should be capitalized.' }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post, optional: true

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  mount_uploader :file, FileUploader
  validates :name, presence: true, format: { with: /\A[A-Z][a-z]+ [a-z]{2,}\.\z/,
                                             message: 'Minimum it should be 2 words with 2 letters each. Should also contain "." and first word should be capitalized.' }
  validate :size_validation

  private

  def size_validation
    errors[:file] << 'should be less than 2MB' if file.size > 2.megabytes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @posts = @category.posts
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = 'Category was successfully created.'
      redirect_to @category
    else
      flash[:error] = @category.errors.full_messages
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category was successfully updated.'
      redirect_to @category
    else
      flash[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = 'Category was successfully destroyed.'
    redirect_to categories_url
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end


    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:new, :create, :destroy]

  def show
  end

  def new
    @post = @category.posts.new
  end

  def edit
  end

  def create
    @post = @category.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to category_path(@category)
    else
      flash[:error] = @post.errors.full_messages
      render :new
    end
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = 'Post was successfully updated.'
      redirect_to @post
    else
      flash[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post was successfully destroyed.'
    redirect_to category_path(@category)
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
          class: "alert fade in alert-#{type} #{tag_class} "
      }.merge(options)

      close_button = content_tag(:button, raw('&times;'), type: 'button', class: 'close', 'data-dismiss' => 'alert')

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
    <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/categories/edit.html.erb
<h1 class="page-header">Editing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="page-header">Categories</h1>
<%= link_to 'New Category', new_category_path %>
<div class="row">
  <div class="col-md-4">
    <% @categories.each do |category| %>
      <h2><%= link_to category.name, category %></h2>
      <%= link_to edit_category_path(category), title: 'Edit Category' do %>
        <span class="glyphicon glyphicon-edit"></span>
      <% end %>
      <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete Category' do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
      <p><%= category.description %></p>
    <% end %>
  </div>
</div>
<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1 class="page-header"><%= @category.name %></h1>
<div class="row">
  <%= link_to 'New Post', new_category_post_path(category_id: @category.id) %>
  <%= link_to edit_category_path(@category), title: 'Edit Category', class: 'col-sm-1' do %>
      <span class="glyphicon glyphicon-edit"></span>
  <% end %>
  <%= link_to categories_path, title: 'Back', class: 'col-sm-1' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
  <% end %>
</div>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-9">
      <hr>
      <h4><%= link_to post.name, post %></h4>
      <%= link_to edit_post_path(post), title: 'Edit Post' do %>
          <span class="glyphicon glyphicon-edit"></span>
      <% end %>
      <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete Post' do %>
          <span class="glyphicon glyphicon-trash"></span>
      <% end %>
      <br>
      <p><%= post.content %></p>
      <p><%= image_tag post.file.url %></p>
    </div>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= comment.author %> at <%= comment.timestamp %> commented</span><br>
          <%= comment.content %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [:category, @post] do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :file %>
    <%= form.file_field :file, class: 'form-control' %>
  </div>
    <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<h1 class="page-header">Editing Post</h1>

<%= render 'form' %>

app/views/posts/new.html.erb
<h1 class="page-header">New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="page-header"><%= @post.name %></h1>
<div class="row">
  <%= link_to edit_post_path(@post), title: 'Edit Post', class: 'col-sm-1' do %>
    <span class="glyphicon glyphicon-edit"></span>
  <% end %>
  <%= link_to category_path(@post.category_id), title: 'Back', class: 'col-sm-1' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
  <% end %>
</div>
<div class="row">
  <div class="col-sm-9">
    <hr>
    <p><%= @post.content %></p>
    <p><%= image_tag @post.file.url %></p>
  </div>
</div>

<div id="comments" data-post-id="<%= @post.id %>">
  <%= render @post.comments if @post.comments.present? %>
</div>

<%= form_for [@post, Comment.new], url: '#' do |f| %>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <%= f.submit 'Add!', class: 'btn btn-primary btn-lg' %>
<% end %>